# Generated by Django 2.0.7 on 2020-08-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(to='accounts.Courses'),
        ),
    ]
