# Generated by Django 2.0.7 on 2020-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Course'),
        ),
    ]
