# Generated by Django 2.0.7 on 2020-08-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='documents',
            field=models.ManyToManyField(blank=True, to='accounts.Document'),
        ),
    ]
