# Generated by Django 2.0.7 on 2020-08-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200803_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attends',
            old_name='classes',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='attends',
            old_name='userProfile',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='userProfiles',
            new_name='userprofiles',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='classes',
            new_name='course',
        ),
    ]
