# Generated by Django 2.0.7 on 2020-08-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200803_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='authored',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authored',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Authored',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
