# Generated by Django 2.0.7 on 2020-08-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_course_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='documents',
        ),
        migrations.AddField(
            model_name='course',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Document'),
        ),
    ]
