# Generated by Django 2.0.7 on 2020-08-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200819_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='documents',
        ),
        migrations.AddField(
            model_name='course',
            name='documents',
            field=models.ManyToManyField(null=True, to='accounts.Document'),
        ),
    ]
