# Generated by Django 2.0.7 on 2020-08-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200819_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='documents',
            field=models.ManyToManyField(to='accounts.Document'),
        ),
    ]
